# Generated by Django 2.2.5 on 2019-09-22 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='text',
        ),
        migrations.AddField(
            model_name='presentation',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presenters',
            field=models.ManyToManyField(related_name='presentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
