version: '3.7'
services:
  postgres:
    restart: always
    image: postgres
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - postgres
